# =============================================================================
# Todo Application - Complete Kubernetes Deployment
# =============================================================================
# This file contains all resources needed to deploy the Todo application.
# Apply with: kubectl apply -f todo-app-all.yaml
# =============================================================================

# -----------------------------------------------------------------------------
# Namespace
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/managed-by: kubectl
---
# -----------------------------------------------------------------------------
# ConfigMaps
# -----------------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-backend
    app.kubernetes.io/component: backend
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SERVER_PORT: "8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-frontend-config
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-frontend
    app.kubernetes.io/component: frontend
data:
  BACKEND_URL: "http://todo-backend-service:8080"
---
# -----------------------------------------------------------------------------
# Backend Deployment
# -----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todo-backend
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: todo-backend
          image: todo-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: todo-backend-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      restartPolicy: Always
---
# -----------------------------------------------------------------------------
# Backend Service (ClusterIP - Internal communication)
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-backend
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: todo-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
---
# -----------------------------------------------------------------------------
# Frontend Deployment
# -----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todo-frontend
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: todo-frontend
          image: todo-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: todo-frontend-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      restartPolicy: Always
---
# -----------------------------------------------------------------------------
# Frontend Service (NodePort - External access)
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-frontend
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: todo-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
