# =============================================================================
# Todo Application - Complete Kubernetes Deployment
# =============================================================================
# This file contains all resources needed to deploy the Todo application.
# Apply with: kubectl apply -f todo-app-all.yaml
# =============================================================================

# -----------------------------------------------------------------------------
# Namespace
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/managed-by: kubectl
---
# -----------------------------------------------------------------------------
# ConfigMaps
# -----------------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-backend
    app.kubernetes.io/component: backend
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SERVER_PORT: "8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-frontend-config
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-frontend
    app.kubernetes.io/component: frontend
data:
  BACKEND_URL: "http://todo-backend-service:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-nginx-config
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-frontend
    app.kubernetes.io/component: frontend
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        # Gzip compression
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        # Handle React Router - serve index.html for all routes
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Proxy API requests to backend (using K8s service name)
        location /api/ {
            proxy_pass http://todo-backend-service:8080/api/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }

        # Cache static assets
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
---
# -----------------------------------------------------------------------------
# Backend Deployment
# -----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todo-backend
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: todo-backend
          image: todo-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: todo-backend-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      restartPolicy: Always
---
# -----------------------------------------------------------------------------
# Backend Service (ClusterIP - Internal communication)
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-backend
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: todo-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
---
# -----------------------------------------------------------------------------
# Frontend Deployment
# -----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todo-frontend
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: todo-frontend
          image: todo-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: todo-frontend-config
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      volumes:
        - name: nginx-config
          configMap:
            name: todo-nginx-config
      restartPolicy: Always
---
# -----------------------------------------------------------------------------
# Frontend Service (NodePort - External access)
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-frontend
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: todo-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
